import React from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  FileText, 
  Sparkles, 
  CheckCircle2, 
  ShieldAlert, 
  ShieldCheck, 
  User, 
  Building2, 
  Calendar, 
  Info,
  Download,
  Share2,
  Stethoscope,
  ArrowRight
} from 'lucide-react';
import toast from 'react-hot-toast';
import { useHealthData } from '../context/HealthDataContext';
import { Card } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';

export const AIAnalysisPage = () => {
  const navigate = useNavigate();
  const { reports, userProfile } = useHealthData();

  const latestReport = (Array.isArray(reports) && reports.length > 0) ? reports[0] : null;
  const biomarkers = Array.isArray(latestReport?.biomarkers) ? latestReport.biomarkers : [
    { id: "b1", name: "Cholesterol (LDL)", value: "135", unit: "mg/dL", refRange: "< 100", status: "Slightly Elevated", statusType: "warning", statusSymbol: "▲", notes: "Consider reducing saturated fats and reviewing routine lipid management." },
    { id: "b2", name: "Hemoglobin (Hb)", value: "13.8", unit: "g/dL", refRange: "12.0 - 15.0", status: "Normal", statusType: "normal", statusSymbol: "✓", notes: "Healthy oxygen-carrying red blood cell baseline." },
    { id: "b3", name: "Glucose (Fasting)", value: "95", unit: "mg/dL", refRange: "70 - 99", status: "Normal", statusType: "normal", statusSymbol: "✓", notes: "Optimal fasting glucose level." }
  ];

  return (
    <div className="space-y-6 pb-12 font-sans antialiased max-w-5xl mx-auto">
      
      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-[#2D90A6] animate-pulse" />
            <span className="text-xs text-[#2D90A6] font-bold uppercase tracking-wider">AI Lab Report Analysis</span>
          </div>
          <h1 className="text-2.5xl font-extrabold text-[#1A4B84] tracking-tight mt-0.5">
            Report Diagnostic Summary
          </h1>
          <p className="text-xs font-normal text-slate-500">
            Structured biomarker parameters and plain-language insights generated by MedGuardian AI
          </p>
        </div>

        <div className="flex gap-2 flex-wrap">
          <Button
            variant="outline"
            size="sm"
            icon={Download}
            className="rounded-xl text-xs font-semibold border-slate-200 cursor-pointer"
            onClick={() => toast.success("Downloading structured report summary PDF...")}
          >
            Export PDF
          </Button>
        </div>
      </div>

      {/* Patient & Report Metadata Header Card */}
      <Card className="p-6 bg-white border border-slate-200 rounded-2xl shadow-xs space-y-4">
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs">
          <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
            <span className="text-slate-500 font-medium flex items-center gap-1">
              <User className="w-3.5 h-3.5 text-[#2D90A6]" /> Patient:
            </span>
            <strong className="text-[#1A4B84] font-bold text-sm block truncate">{userProfile?.name || "Sarah Jenkins"}</strong>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
            <span className="text-slate-500 font-medium flex items-center gap-1">
              <FileText className="w-3.5 h-3.5 text-[#2D90A6]" /> Report Type:
            </span>
            <strong className="text-[#1A4B84] font-bold text-sm block truncate">{latestReport?.title || "Comprehensive Metabolic Panel"}</strong>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
            <span className="text-slate-500 font-medium flex items-center gap-1">
              <Calendar className="w-3.5 h-3.5 text-[#2D90A6]" /> Date:
            </span>
            <strong className="text-[#1A4B84] font-bold text-sm block">{latestReport?.date || "Oct 24, 2023"}</strong>
          </div>

          <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
            <span className="text-slate-500 font-medium flex items-center gap-1">
              <Building2 className="w-3.5 h-3.5 text-[#2D90A6]" /> Hospital / Lab:
            </span>
            <strong className="text-[#1A4B84] font-bold text-sm block truncate">{latestReport?.labName || "City Hospital Diagnostics"}</strong>
          </div>
        </div>
      </Card>

      {/* AI Summary Card */}
      <Card className="p-6 bg-gradient-to-r from-[#1A4B84] to-[#143A66] text-white rounded-2xl shadow-md space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-xl bg-white/10 flex items-center justify-center border border-white/20">
              <Sparkles className="w-4.5 h-4.5 text-[#2D90A6]" />
            </div>
            <h3 className="text-base font-extrabold text-white">AI Clinical Summary</h3>
          </div>
          <span className="px-2.5 py-0.5 rounded-full bg-[#2D90A6]/30 text-[#CCFBF1] text-xs font-bold border border-[#2D90A6]/40">
            Report Parsed ✓
          </span>
        </div>

        <p className="text-sm text-slate-100 leading-relaxed font-normal">
          {latestReport?.aiSummary || "Your results are mostly within normal ranges. A few values (Cholesterol LDL) require attention and routine review with your healthcare provider."}
        </p>
      </Card>

      {/* Individual Findings Table / Cards */}
      <Card className="p-6 bg-white border border-slate-200 rounded-2xl shadow-xs space-y-4">
        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <h3 className="text-base font-extrabold text-[#1A4B84]">Individual Biomarker Findings</h3>
          <span className="text-xs text-slate-500 font-medium">{biomarkers.length} Parameters Parsed</span>
        </div>

        <div className="space-y-3">
          {biomarkers.map((bm, idx) => {
            const isWarning = bm.statusType === 'warning' || bm.status === 'Slightly Elevated' || bm.status === 'High';
            const isCritical = bm.statusType === 'critical';

            return (
              <div 
                key={bm.id || idx}
                className="p-4 rounded-xl bg-slate-50 border border-slate-200/90 flex flex-col sm:flex-row sm:items-center justify-between gap-3"
              >
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <h4 className="font-extrabold text-sm text-[#1A4B84]">{bm.name}</h4>
                    <span className={`med-badge ${
                      isCritical
                        ? 'med-badge-critical'
                        : isWarning
                        ? 'med-badge-warning'
                        : 'med-badge-normal'
                    }`}>
                      <span>{bm.statusSymbol || (isWarning ? '▲' : '✓')}</span>
                      <span>{bm.status}</span>
                    </span>
                  </div>

                  <p className="text-xs text-slate-600 font-normal">{bm.notes || 'Parameter measured within expected parameters.'}</p>
                </div>

                <div className="text-right sm:text-right shrink-0">
                  <span className="text-base font-extrabold text-[#1A4B84] block">
                    {bm.value} <span className="text-xs font-normal text-slate-500">{bm.unit}</span>
                  </span>
                  <span className="text-[11px] text-slate-500 font-medium block">Ref: {bm.refRange}</span>
                </div>
              </div>
            );
          })}
        </div>
      </Card>

      {/* Mandatory Medical Disclaimer Banner */}
      <div className="p-4 rounded-xl bg-slate-100 border border-slate-200 text-xs text-slate-600 flex items-start gap-2.5">
        <Info className="w-4 h-4 text-[#1A4B84] shrink-0 mt-0.5" />
        <p className="leading-relaxed font-normal">
          <strong>Mandatory Medical Disclaimer:</strong> AI-generated information is for informational purposes only and should not replace professional medical advice. Always consult a qualified healthcare provider for clinical evaluation.
        </p>
      </div>

    </div>
  );
};
